---
# tasks file for .
- name: Run task on CentOS
  import_tasks: Centos.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Run task on Debian
  import_tasks: Debian.yml
  when: ansible_facts['os_family']|lower == 'debian'
