---
- name: "install required packages"
  package:
   name: "{{ item.name }}"
   state: "{{ item.state }}"
   update_cache: true
  with_items: "{{ base_soft_list }}"

- name: "install extra packages"
  package:
   name: "{{ item.name }}"
   state: "{{ item.state }}"
   update_cache: true
  with_items: "{{ base_soft_list_extra }}"
