---
# tasks file for .
- name: Run master task
  import_tasks: Centos.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- import_tasks: Debian.yml
  when: ansible_facts['os_family']|lower == 'debian'