---
- name: "update apt cache"
  apt:
    update_cache: true

- name: "install required packages"
  apt:
   name: "{{ item.name }}"
   state: "{{ item.state }}"
   update_cache: true
  with_items: "{{ base_soft_list }}"

- name: "install extra packages"
  apt:
   name: "{{ item.name }}"
   state: "{{ item.state }}"
   update_cache: true
  with_items: "{{ base_soft_list_extra }}"
