---

- name: "install_base_soft | include OS-specific variables."
  include_vars: "{{ ansible_os_family }}.yml"

- name: "install_base_soft | update apt cache."
  yum:
    update_cache: true
    cache_valid_time: 86400
  when: ansible_os_family == 'RedHat'

- name: "install_base_soft | install required packages."
  yum:
   name: "{{ item.name }}"
   state: "{{ item.state }}"
   update_cache: false
  with_items: "{{ base_soft_list }}"
  when: ansible_os_family == 'RedHat'

- name: "install_base_soft | install extra packages."
  yum:
   name: "{{ item.name }}"
   state: "{{ item.state }}"
   update_cache: false
  with_items: "{{ base_soft_list_extra }}"
  when: ansible_os_family == 'RedHat'
